eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
server:
  port: 8082
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client-one
    api-b:
      path: /api-b/**
      serviceId: client-two
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000